Spring:
  application:
    name: forum

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 980515Qq!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 静态资源配置
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  mvc:
    throw-exception-if-no-handler-found: false

# 配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 驼峰命名
# 扫描mapper
  mapper-locations: classpath:mapper/**/*.xml

# 日志
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss
  level:
    root: info

# SpringDoc OpenAPI 3 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: cn.iocoder.forum.controller